### ISSUE TITLE
Cannot handel big txt files

### ISSUE THREAD

**Issue by anandunofficial** [Kalebu/Plagiarism-checker-Python#2] opened 2021-05-23 18:34 UTC
in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 832: character ma
ps to <undefined>

**Comment by Kalebu** [comment] 2021-05-24 07:31
Hello @anandunofficial I think this is due to the fact encoding wasn't specified, I have updated the codebase with UTF-8 encoding, can you try running again and let me know how it goes?

**Comment by anandunofficial** [comment] 2021-05-26 13:43
yes you were correct because the encoding was not mentioned it did not work properly
but its working fine now
I'd love if you could provide some documentation on the method used

**Comment by Kalebu** [comment] 2021-05-26 13:55
The method used is **Cosine similarity**, 
you can learn more about it at[ official sklearn documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html).

I will assume the issue is fixed, I'm closing it , Thanks for reporting it

**Closed as completed by Kalebu** 2021-05-26 13:55 UTC

**Comment by anandunofficial** [comment] 2021-05-26 13:59
> The method used is **Cosine similarity**,
> you can learn more about it at[ official sklearn documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html).
> 
> I will assume the issue is fixed, I'm closing it , Thanks for reporting it

Yes it's fixes 
but man you are quick
